### ISSUE TITLE
contracts call error

### ISSUE THREAD

**Issue by HAOYUatHZ** [fluidex/contracts.demo#22]
```

eth_estimateGas
  Contract call:           FluidexDemo#submitBlock
  From:                    0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                      0x5fbdb2315678afecb367f032d93f642f64180aa3
  Value:                   0 ETH

  Error: VM Exception while processing transaction: invalid opcode
      at FluidexDemo.submitBlock (contracts/Fluidex.sol:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at EthModule._estimateGasAction (/home/chris/gitfiles/fluidex/fluidex-backend/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:421:9)
      at HardhatNetworkProvider._sendWithLogging (/home/chris/gitfiles/fluidex/fluidex-backend/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:126:22)
      at HardhatNetworkProvider.request (/home/chris/gitfiles/fluidex/fluidex-backend/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:103:18)
      at JsonRpcHandler._handleRequest (/home/chris/gitfiles/fluidex/fluidex-backend/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/home/chris/gitfiles/fluidex/fluidex-backend/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/home/chris/gitfiles/fluidex/fluidex-backend/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

when using https://github.com/fluidex/contracts.demo/commit/c36e354913328c8d171c26811aab101d4b4befd9

**Comment by HAOYUatHZ** [comment]
may not re-produce

**Comment by HAOYUatHZ** [comment]
close for now
